name: inventario_y_facturacion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3      # SQLite para Windows (desktop)
  path: ^1.9.0                     # Para rutas de archivos
  path_provider: ^2.1.4            # Rutas del sistema (AppData) — necesario para MSIX
  provider: ^6.1.2                 # Manejo de estado
  intl: ^0.19.0                    # Formato de fechas y moneda
  shared_preferences: ^2.3.2       # Guardar config de empresa
  image_picker: ^1.1.2             # Seleccionar logo
  pdf: ^3.11.1                     # Generar facturas PDF
  printing: ^5.13.1                # Imprimir / exportar PDF
  file_selector: ^0.9.3+2          # Selector de archivos/carpetas (backup)
  excel: ^4.0.6                     # Exportar datos a Excel (.xlsx)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: Anthony Design
  publisher_display_name: Anthony Design
  identity_name: com.anthonydesign.inventario
  msix_version: 1.0.0.0
  logo_path: windows\runner\resources\app_icon.ico
  capabilities: fileOpenPicker, fileSavePicker, picturesLibrary
